# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Joshua-DinG
email: admin@admin.com
description:  小孩才分对错，成人只看利弊。
baseurl: "/DinG" # the subpath of your site, e.g. /blog
url: "http://xxxxx.com" # the base hostname & protocol for your site
twitter_username: DinG
github_username:  DinG

# Build settings
markdown: kramdown
highlight_theme: tomorrow-night

